wget -O /var/lib/jenkins/plugins/ace-editor.jpi                          https://updates.jenkins-ci.org/latest/ace-editor.hpi
wget -O /var/lib/jenkins/plugins/ant.jpi                                 https://updates.jenkins-ci.org/latest/ant.hpi
wget -O /var/lib/jenkins/plugins/antisamy-markup-formatter.jpi           https://updates.jenkins-ci.org/latest/antisamy-markup-formatter.hpi
wget -O /var/lib/jenkins/plugins/apache-httpcomponents-client-4-api.jpi  https://updates.jenkins-ci.org/latest/apache-httpcomponents-client-4-api.hpi
wget -O /var/lib/jenkins/plugins/bootstrap5-api.jpi                      https://updates.jenkins-ci.org/latest/bootstrap5-api.hpi
wget -O /var/lib/jenkins/plugins/bouncycastle-api.jpi                    https://updates.jenkins-ci.org/latest/bouncycastle-api.hpi
wget -O /var/lib/jenkins/plugins/branch-api.jpi                          https://updates.jenkins-ci.org/latest/branch-api.hpi
wget -O /var/lib/jenkins/plugins/build-timeout.jpi                       https://updates.jenkins-ci.org/latest/build-timeout.hpi
wget -O /var/lib/jenkins/plugins/caffeine-api.jpi                        https://updates.jenkins-ci.org/latest/caffeine-api.hpi
wget -O /var/lib/jenkins/plugins/checks-api.jpi                          https://updates.jenkins-ci.org/latest/checks-api.hpi
wget -O /var/lib/jenkins/plugins/cloudbees-folder.jpi                    https://updates.jenkins-ci.org/latest/cloudbees-folder.hpi
wget -O /var/lib/jenkins/plugins/command-launcher.jpi                    https://updates.jenkins-ci.org/latest/command-launcher.hpi
wget -O /var/lib/jenkins/plugins/credentials-binding.jpi                 https://updates.jenkins-ci.org/latest/credentials-binding.hpi
wget -O /var/lib/jenkins/plugins/credentials.jpi                         https://updates.jenkins-ci.org/latest/credentials.hpi
wget -O /var/lib/jenkins/plugins/display-url-api.jpi                     https://updates.jenkins-ci.org/latest/display-url-api.hpi
wget -O /var/lib/jenkins/plugins/durable-task.jpi                        https://updates.jenkins-ci.org/latest/durable-task.hpi
wget -O /var/lib/jenkins/plugins/echarts-api.jpi                         https://updates.jenkins-ci.org/latest/echarts-api.hpi
wget -O /var/lib/jenkins/plugins/email-ext.jpi                           https://updates.jenkins-ci.org/latest/email-ext.hpi
wget -O /var/lib/jenkins/plugins/font-awesome-api.jpi                    https://updates.jenkins-ci.org/latest/font-awesome-api.hpi
wget -O /var/lib/jenkins/plugins/git-client.jpi                          https://updates.jenkins-ci.org/latest/git-client.hpi
wget -O /var/lib/jenkins/plugins/git-server.jpi                          https://updates.jenkins-ci.org/latest/git-server.hpi
wget -O /var/lib/jenkins/plugins/git.jpi                                 https://updates.jenkins-ci.org/latest/git.hpi
wget -O /var/lib/jenkins/plugins/github-api.jpi                          https://updates.jenkins-ci.org/latest/github-api.hpi
wget -O /var/lib/jenkins/plugins/github-branch-source.jpi                https://updates.jenkins-ci.org/latest/github-branch-source.hpi
wget -O /var/lib/jenkins/plugins/github.jpi                              https://updates.jenkins-ci.org/latest/github.hpi
wget -O /var/lib/jenkins/plugins/gradle.jpi                              https://updates.jenkins-ci.org/latest/gradle.hpi
wget -O /var/lib/jenkins/plugins/handlebars.jpi                          https://updates.jenkins-ci.org/latest/handlebars.hpi
wget -O /var/lib/jenkins/plugins/jackson2-api.jpi                        https://updates.jenkins-ci.org/latest/jackson2-api.hpi
wget -O /var/lib/jenkins/plugins/javax-activation-api.jpi                https://updates.jenkins-ci.org/latest/javax-activation-api.hpi
wget -O /var/lib/jenkins/plugins/javax-mail-api.jpi                      https://updates.jenkins-ci.org/latest/javax-mail-api.hpi
wget -O /var/lib/jenkins/plugins/jaxb.jpi                                https://updates.jenkins-ci.org/latest/jaxb.hpi
wget -O /var/lib/jenkins/plugins/jdk-tool.jpi                            https://updates.jenkins-ci.org/latest/jdk-tool.hpi
wget -O /var/lib/jenkins/plugins/jjwt-api.jpi                            https://updates.jenkins-ci.org/latest/jjwt-api.hpi
wget -O /var/lib/jenkins/plugins/jquery3-api.jpi                         https://updates.jenkins-ci.org/latest/jquery3-api.hpi
wget -O /var/lib/jenkins/plugins/jsch.jpi                                https://updates.jenkins-ci.org/latest/jsch.hpi
wget -O /var/lib/jenkins/plugins/junit.jpi                               https://updates.jenkins-ci.org/latest/junit.hpi
wget -O /var/lib/jenkins/plugins/ldap.jpi                                https://updates.jenkins-ci.org/latest/ldap.hpi
wget -O /var/lib/jenkins/plugins/mailer.jpi                              https://updates.jenkins-ci.org/latest/mailer.hpi
wget -O /var/lib/jenkins/plugins/matrix-auth.jpi                         https://updates.jenkins-ci.org/latest/matrix-auth.hpi
wget -O /var/lib/jenkins/plugins/matrix-project.jpi                      https://updates.jenkins-ci.org/latest/matrix-project.hpi
wget -O /var/lib/jenkins/plugins/momentjs.jpi                            https://updates.jenkins-ci.org/latest/momentjs.hpi
wget -O /var/lib/jenkins/plugins/okhttp-api.jpi                          https://updates.jenkins-ci.org/latest/okhttp-api.hpi
wget -O /var/lib/jenkins/plugins/pam-auth.jpi                            https://updates.jenkins-ci.org/latest/pam-auth.hpi
wget -O /var/lib/jenkins/plugins/pipeline-build-step.jpi                 https://updates.jenkins-ci.org/latest/pipeline-build-step.hpi
wget -O /var/lib/jenkins/plugins/pipeline-github-lib.jpi                 https://updates.jenkins-ci.org/latest/pipeline-github-lib.hpi
wget -O /var/lib/jenkins/plugins/pipeline-graph-analysis.jpi             https://updates.jenkins-ci.org/latest/pipeline-graph-analysis.hpi
wget -O /var/lib/jenkins/plugins/pipeline-input-step.jpi                 https://updates.jenkins-ci.org/latest/pipeline-input-step.hpi
wget -O /var/lib/jenkins/plugins/pipeline-milestone-step.jpi             https://updates.jenkins-ci.org/latest/pipeline-milestone-step.hpi
wget -O /var/lib/jenkins/plugins/pipeline-model-api.jpi                  https://updates.jenkins-ci.org/latest/pipeline-model-api.hpi
wget -O /var/lib/jenkins/plugins/pipeline-model-definition.jpi           https://updates.jenkins-ci.org/latest/pipeline-model-definition.hpi
wget -O /var/lib/jenkins/plugins/pipeline-model-extensions.jpi           https://updates.jenkins-ci.org/latest/pipeline-model-extensions.hpi
wget -O /var/lib/jenkins/plugins/pipeline-rest-api.jpi                   https://updates.jenkins-ci.org/latest/pipeline-rest-api.hpi
wget -O /var/lib/jenkins/plugins/pipeline-stage-step.jpi                 https://updates.jenkins-ci.org/latest/pipeline-stage-step.hpi
wget -O /var/lib/jenkins/plugins/pipeline-stage-tags-metadata.jpi        https://updates.jenkins-ci.org/latest/pipeline-stage-tags-metadata.hpi
wget -O /var/lib/jenkins/plugins/pipeline-stage-view.jpi                 https://updates.jenkins-ci.org/latest/pipeline-stage-view.hpi
wget -O /var/lib/jenkins/plugins/plain-credentials.jpi                   https://updates.jenkins-ci.org/latest/plain-credentials.hpi
wget -O /var/lib/jenkins/plugins/plugin-util-api.jpi                     https://updates.jenkins-ci.org/latest/plugin-util-api.hpi
wget -O /var/lib/jenkins/plugins/popper2-api.jpi                         https://updates.jenkins-ci.org/latest/popper2-api.hpi
wget -O /var/lib/jenkins/plugins/resource-disposer.jpi                   https://updates.jenkins-ci.org/latest/resource-disposer.hpi
wget -O /var/lib/jenkins/plugins/scm-api.jpi                             https://updates.jenkins-ci.org/latest/scm-api.hpi
wget -O /var/lib/jenkins/plugins/script-security.jpi                     https://updates.jenkins-ci.org/latest/script-security.hpi
wget -O /var/lib/jenkins/plugins/snakeyaml-api.jpi                       https://updates.jenkins-ci.org/latest/snakeyaml-api.hpi
wget -O /var/lib/jenkins/plugins/ssh-credentials.jpi                     https://updates.jenkins-ci.org/latest/ssh-credentials.hpi
wget -O /var/lib/jenkins/plugins/ssh-slaves.jpi                          https://updates.jenkins-ci.org/latest/ssh-slaves.hpi
wget -O /var/lib/jenkins/plugins/sshd.jpi                                https://updates.jenkins-ci.org/latest/sshd.hpi
wget -O /var/lib/jenkins/plugins/structs.jpi                             https://updates.jenkins-ci.org/latest/structs.hpi
wget -O /var/lib/jenkins/plugins/timestamper.jpi                         https://updates.jenkins-ci.org/latest/timestamper.hpi
wget -O /var/lib/jenkins/plugins/token-macro.jpi                         https://updates.jenkins-ci.org/latest/token-macro.hpi
wget -O /var/lib/jenkins/plugins/trilead-api.jpi                         https://updates.jenkins-ci.org/latest/trilead-api.hpi
wget -O /var/lib/jenkins/plugins/variant.jpi                             https://updates.jenkins-ci.org/latest/variant.hpi
wget -O /var/lib/jenkins/plugins/workflow-aggregator.jpi                 https://updates.jenkins-ci.org/latest/workflow-aggregator.hpi
wget -O /var/lib/jenkins/plugins/workflow-api.jpi                        https://updates.jenkins-ci.org/latest/workflow-api.hpi
wget -O /var/lib/jenkins/plugins/workflow-basic-steps.jpi                https://updates.jenkins-ci.org/latest/workflow-basic-steps.hpi
wget -O /var/lib/jenkins/plugins/workflow-cps-global-lib.jpi             https://updates.jenkins-ci.org/latest/workflow-cps-global-lib.hpi
wget -O /var/lib/jenkins/plugins/workflow-cps.jpi                        https://updates.jenkins-ci.org/latest/workflow-cps.hpi
wget -O /var/lib/jenkins/plugins/workflow-durable-task-step.jpi          https://updates.jenkins-ci.org/latest/workflow-durable-task-step.hpi
wget -O /var/lib/jenkins/plugins/workflow-job.jpi                        https://updates.jenkins-ci.org/latest/workflow-job.hpi
wget -O /var/lib/jenkins/plugins/workflow-multibranch.jpi                https://updates.jenkins-ci.org/latest/workflow-multibranch.hpi
wget -O /var/lib/jenkins/plugins/workflow-scm-step.jpi                   https://updates.jenkins-ci.org/latest/workflow-scm-step.hpi
wget -O /var/lib/jenkins/plugins/workflow-step-api.jpi                   https://updates.jenkins-ci.org/latest/workflow-step-api.hpi
wget -O /var/lib/jenkins/plugins/workflow-support.jpi                    https://updates.jenkins-ci.org/latest/workflow-support.hpi
wget -O /var/lib/jenkins/plugins/ws-cleanup.jpi                          https://updates.jenkins-ci.org/latest/ws-cleanup.hpi
wget -O /var/lib/jenkins/plugins/pipeline-groovy-lib.jpi                 https://updates.jenkins-ci.org/latest/pipeline-groovy-lib.hpi
wget -O /var/lib/jenkins/plugins/docker-workflow.jpi                     https://updates.jenkins-ci.org/latest/docker-workflow.hpi
wget -O /var/lib/jenkins/plugins/docker-plugin.jpi                       https://updates.jenkins-ci.org/latest/docker-plugin.hpi
wget -O /var/lib/jenkins/plugins/docker-commons.jpi                      https://updates.jenkins-ci.org/latest/docker-commons.hpi
wget -O /var/lib/jenkins/plugins/docker-java-api.jpi                     https://updates.jenkins-ci.org/latest/docker-java-api.hpi
wget -O /var/lib/jenkins/plugins/authentication-tokens.jpi               https://updates.jenkins-ci.org/latest/authentication-tokens.hpi
wget -O /var/lib/jenkins/plugins/publish-over-ssh.jpi                    https://updates.jenkins-ci.org/latest/publish-over-ssh.hpi
wget -O /var/lib/jenkins/plugins/publish-over.jpi                        https://updates.jenkins-ci.org/latest/publish-over.hpi